### PR TITLE
Exposed getValue from widget.

### PR DESCRIPTION
**Pull request by Adipa**
To help see the current value of the widget in code.

### CODE REVIEW

**Comment by manumaticx** [comment]
Can you also add this to the $.container please? (here: https://github.com/manumaticx/circularprogress/blob/22cd95f4b81e6e156aa0f5b5d803511113bdd14d/de.manumaticx.circularprogress/controllers/widget.js#L92)

thanks! :)

**Comment by Adipa** [comment]
Yeah sure let me get on that.

**Comment by Adipa** [comment]
@manumaticx Hey sorry for the delay, I added that. 

Also thank you making it, we needed a circular balance counter for our mobile app (save.ca) and it really saved a lot of time. 
screen shot 2015-04-24 at 9 41 03 am

**Comment by manumaticx** [comment]
Super cool! This looks very nice! :+1:

**Comment by manumaticx** [comment]
and thanks for the pull request :)

**Comment by rondog** [comment]
I'm glad so many have found this useful. The awesome thing is I made an angularjs version of this and it was near identical code

**Pull request merged**
