### PR TITLE
Update widget.js

### PR DESCRIPTION
**Pull request by GerbenHofman**
Added a showPercentage option, when true it will add a '%' to the value. Tested on Android and IOS.

### CODE REVIEW

**Comment by manumaticx** [comment]
You can actually do this already with the `formatValue` option to modify the value to whatever you want ;)

**Comment by GerbenHofman** [comment]
Ah I see, I pulled an older version from gitTio which didn't had the format function ^^.

**Comment by manumaticx** [comment]
Oh, I forgot to bump the version. sorry

**Comment by manumaticx** [comment]
I should also write a little documentation :see_no_evil:

**Pull request closed without merging**
